version: "3.3"

services:
  aptly:
    image: ieperez/docker-aptly
    environment:
      - WEBUI=yes
    volumes:
      - ./aptly:/srv/aptly
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 20s
      retries: 3

  web:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./aptly/public:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - aptly
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 20s
      retries: 3

  ftp:
    image: stilliard/pure-ftpd
    environment:
      - PUBLICHOST=localhost
    #  - ADDED_FLAGS=--tls=2
    volumes:
      - ./aptly/public:/home/ftpusers
    ports:
      - "21:21"
      - "20:20"
      - "30000-30059:30000-30059"
    depends_on:
      - aptly
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "curl", "-f", "ftp://localhost:21"]
      interval: 1m30s
      timeout: 20s
      retries: 3
